In [1]:
from numpy import loadtxt

In [2]:
data=loadtxt('wind.data')

In [3]:
data

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

In [4]:
data.shape

(6574, 15)

In [11]:
dataloc=data[:,3:]

In [12]:
dataloc.shape

(6574, 12)

In [13]:
dataloc

array([[15.04, 14.96, 13.17, ..., 12.58, 18.5 , 15.04],
       [14.71, 16.88, 10.83, ...,  9.67, 17.54, 13.83],
       [18.5 , 16.88, 12.33, ...,  7.67, 12.75, 12.71],
       ...,
       [14.  , 10.29, 14.42, ..., 16.42, 18.88, 29.58],
       [18.5 , 14.04, 21.29, ..., 12.12, 14.67, 28.79],
       [20.33, 17.41, 27.29, ..., 11.38, 12.08, 22.08]])

In [14]:
#Question 2 $ 3

dataloc.min(axis=0)

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [15]:
dataloc.max(axis=0)

array([35.8 , 33.37, 33.84, 28.46, 37.54, 26.16, 30.37, 31.08, 25.88,
       28.21, 42.38, 42.54])

In [19]:
dataloc.std(axis=0)

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

In [26]:
dataloc.mean()

10.22837377040868

In [25]:
dataloc.std()


5.603840181095793

In [24]:
dataloc.max()


42.54

In [22]:
dataloc.min()


0.0

In [18]:
#Question 4

In [30]:
dataloc.min(axis=1)

array([9.29, 6.5 , 6.17, ..., 8.71, 9.13, 9.59])

In [31]:
dataloc.max(axis=1)

array([18.5 , 17.54, 18.5 , ..., 29.58, 28.79, 27.29])

In [32]:
dataloc.mean(axis=1)

array([13.09666667, 11.79833333, 11.34166667, ..., 14.89      ,
       15.3675    , 15.4025    ])

In [33]:
dataloc.std(axis=1)

array([2.5773188 , 3.28972854, 3.50543348, ..., 5.51175108, 5.30456427,
       5.45971172])

In [34]:
#Question 5

In [50]:
dataloc.argmax(axis=1)
    

array([10, 10,  0, ..., 11, 11,  2], dtype=int64)

In [51]:
datadate=data[:,:3]

In [52]:
datadate

array([[61.,  1.,  1.],
       [61.,  1.,  2.],
       [61.,  1.,  3.],
       ...,
       [78., 12., 29.],
       [78., 12., 30.],
       [78., 12., 31.]])

In [54]:
np.where(dataloc==dataloc.max())

(array([2161], dtype=int64), array([11], dtype=int64))

In [56]:
datadate[2161]

array([66., 12.,  2.])

In [57]:
dataloc.argmax()

25943

In [59]:
np.unravel_index(dataloc.argmax(),dataloc.shape)

(2161, 11)

In [62]:
dataloc.max(axis=1).argmax()

2161

In [64]:
January=datadate[:,1]==1

In [65]:
January.shape

(6574,)

In [67]:
dataloc[January].mean(axis=0)

array([14.86955197, 12.92166667, 13.29962366,  7.19949821, 11.67571685,
        8.05483871, 11.81935484,  9.5094086 ,  9.54320789, 10.05356631,
       14.55051971, 18.02876344])