In [2]:
import numpy as np

a=np.array([-1,-3,1,3,4,5,3,-8])

In [3]:
a

array([-1, -3,  1,  3,  4,  5,  3, -8])

In [10]:
a<0

array([ True,  True, False, False, False, False, False,  True])

In [11]:
negative=a<0

In [12]:
[negative]

[array([ True,  True, False, False, False, False, False,  True])]

In [15]:
a=np.arange(49).reshape(7,7)

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [18]:
b=np.array([[0,1,2,3,4,5],
          [10,11,12,13,14,15],
          [20,21,22,23,24,25],
          [30,31,32,33,34,35],
          [40,41,42,43,44,45],
          [50,51,52,53,54,55]])

In [19]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [20]:
b[[0,1,2,3,4],[1,2,3,4,5]]

array([ 1, 12, 23, 34, 45])

In [21]:
b[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [22]:
mask=np.array([1,0,1,0,0,1], dtype=bool)
b[mask,2]

array([ 2, 22, 52])

In [23]:
b[[0,2,5],2]

array([ 2, 22, 52])

In [24]:
a=np.arange(25).reshape(5,5)

In [25]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
a[[0,2,3,3],[2,3,1,4]]

array([ 2, 13, 16, 19])

In [30]:
a%3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]], dtype=int32)

In [31]:
a%3==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [32]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [41]:
a=np.ones((5,6))

In [42]:
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
a.sum(axis=-1)

array([6., 6., 6., 6., 6.])

In [44]:
a.sum(axis=0)

array([5., 5., 5., 5., 5., 5.])

In [46]:
a.sum()

30.0