In [3]:
import numpy as np

In [6]:
a=np.array([1,3,3,4])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [24]:
f=np.array([3.4,2.4,2.1,3.9])

In [10]:
type(f)

numpy.ndarray

In [11]:
f.dtype

dtype('float64')

In [12]:
a



array([1, 3, 3, 4])

In [14]:
a[0]

1

In [15]:
a[0]=10

In [16]:
a

array([10,  3,  3,  4])

In [17]:
a.ndim

1

In [19]:
a.shape

(4,)

In [20]:
a.size

4

In [25]:
a

array([10,  3,  3,  4])

In [26]:
f

array([3.4, 2.4, 2.1, 3.9])

In [27]:
a+f

array([13.4,  5.4,  5.1,  7.9])

In [28]:
a*f

array([34. ,  7.2,  6.3, 15.6])

In [29]:
a/f

array([2.94117647, 1.25      , 1.42857143, 1.02564103])

In [30]:
a**f

array([2511.88643151,   13.96661017,   10.04510857,  222.8609442 ])

In [31]:
f**a

array([2.06437775e+05, 1.38240000e+01, 9.26100000e+00, 2.31344100e+02])

In [32]:
a

array([10,  3,  3,  4])

In [33]:
a*10

array([100,  30,  30,  40])

In [34]:
#universal functions

np.sin(a)

array([-0.54402111,  0.14112001,  0.14112001, -0.7568025 ])

In [36]:
a=np.array([[1,2,3,4],
           [3,5,4,2]])

In [37]:
a

array([[1, 2, 3, 4],
       [3, 5, 4, 2]])

In [38]:
a.shape

(2, 4)

In [39]:
a.size

8

In [40]:
a.ndim

2

In [41]:
a[1,3]

2

In [42]:
a[1]

array([3, 5, 4, 2])

In [43]:
a

array([[1, 2, 3, 4],
       [3, 5, 4, 2]])

In [44]:
b=np.array([1,3,4,5])

In [45]:
b

array([1, 3, 4, 5])

In [46]:
b[1]

3

In [47]:
b[1:3]

array([3, 4])

In [48]:
b[-4:3]

array([1, 3, 4])

In [55]:
a=np.arange(25).reshape(5,5)

In [56]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
b=np.arange(30)

In [53]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [74]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
a[4,:]

array([20, 21, 22, 23, 24])

In [76]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [83]:
a[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [84]:
a=np.array([1,2,3,4])

In [85]:
a

array([1, 2, 3, 4])

In [86]:
b=a[:2]

In [87]:
b

array([1, 2])

In [88]:
b[0]

1

In [89]:
b[0]=-1

In [90]:
b

array([-1,  2])

In [91]:
a

array([-1,  2,  3,  4])

In [92]:
b=a.copy()

In [93]:
b

array([-1,  2,  3,  4])

In [94]:
b[-2:]=[-1,-4]

In [95]:
b

array([-1,  2, -1, -4])